meritz.bridge.base-url=http://211.220.195.17:18080

# TPA - 개발/테스트용
companies.configs.tpa.client-id=810bf258913a4fcf8709b7dac97ceadd
companies.configs.tpa.client-secret=f89223fa6e3d407f91e735908ce1cf2d
companies.configs.tpa.company-code=TPA
companies.configs.tpa.aflco-div-cd=TPA
companies.configs.tpa.gnr-aflco-cd=020

# TPA 사업자등록번호
companies.configs.tpa.bizpeNo=2368801872

