logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG

portone:
  v1:
    base-url: https://api.iamport.kr
    api-key: ${PORTONE_API_KEY}
    api-secret: ${PORTONE_API_SECRET}
    timeout-ms: 5000


aligo:
  api-key: ${ALIGO_API_KEY}
  user-id: ${ALIGO_USER_ID}
  sender: ${ALIGO_PHONE}
  sender-key: ${ALIGO_SENDER_KEY}
  token: ${ALIGO_TOKEN:}   # 없을 수도 있으니 기본값 빈값


companies:
  configs:
    tpa:
      clientId: ${COMPANIES_CONFIGS_TPA_CLIENTID}
      clientSecret: ${COMPANIES_CONFIGS_TPA_CLIENTSECRET}
      companyCode: ${COMPANIES_CONFIGS_TPA_COMPANYCODE}
      aflcoDivCd: ${COMPANIES_CONFIGS_TPA_AFLCODIVCD}
      gnrAflcoCd: ${COMPANIES_CONFIGS_TPA_GNRAFLCOCD}
      bizpeNo: ${COMPANIES_CONFIGS_TPA_BIZPENO}
    insboon:
      clientId: ${COMPANIES_CONFIGS_INSBOON_CLIENTID:}
      clientSecret: ${COMPANIES_CONFIGS_INSBOON_CLIENTSECRET:}
      companyCode: ${COMPANIES_CONFIGS_INSBOON_COMPANYCODE:INSBOON}
      aflcoDivCd: ${COMPANIES_CONFIGS_INSBOON_AFLCODIVCD:INSBOON}
      gnrAflcoCd: ${COMPANIES_CONFIGS_INSBOON_GNRAFLCOCD:}
      bizpeNo: ${COMPANIES_CONFIGS_INSBOON_BIZPENO:}