# 운영 환경 민감 정보 (Git에서 제외, 별도 관리)
# 이 파일은 .gitignore에 추가되어야 합니다
# 운영 서버에만 존재해야 하며, 암호화된 형태로 관리 권장
# 풍수해: 019
# 여행자: 020


# 운영 환경 - 인스보온 API 인증 정보 (실제 운영)
companies.configs.insboon.hostUrl=https://bizapi.meritzfire.com:25200
companies.configs.insboon.clientId=61a6149aa46b4308ae8d001713718217
companies.configs.insboon.clientSecret=7fe4d5130b0c4207b425ca5b1dda9cda
companies.configs.insboon.companyCode=INSBOON
companies.configs.insboon.aflcoDivCd=NEXSOL
companies.configs.insboon.gnrAflcoCd=007

# 운영 환경 - TPA API 인증 정보 (실제 운영)
companies.configs.tpa.hostUrl=https://bizapi.meritzfire.com:25200
companies.configs.tpa.clientId=8c01f6bf9c594fec869cbde56d48d69a
companies.configs.tpa.clientSecret=fabc8a72355a459b9ce22bd5f9623d0b
companies.configs.tpa.companyCode=TPA
companies.configs.tpa.aflcoDivCd=TPA
companies.configs.tpa.gnrAflcoCd=020
# TPA 사업자등록번호
companies.configs.tpa.bizpeNo=2368801872

# MySQL 데이터베이스의 URL 설정
spring.datasource.url=jdbc:mysql://211.220.195.13:13306/tpa_db
# 데이터베이스 사용자명
spring.datasource.username=nexsol_web
# 데이터베이스 비밀번호
spring.datasource.password=sprthf9!0boon
# MySQL JDBC 드라이버 클래스 설정
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#### HikariCP 연결 풀 설정 ####
# 최대 풀 크기 (최대 커넥션 수)
# spring.datasource.hikari.maximum-pool-size=10
# 최소 유휴 커넥션 수
# spring.datasource.hikari.minimum-idle=5

# 커넥션 풀에서 사용하는 데이터베이스 커넥션 테스트 쿼리 (옵션)
# spring.datasource.hikari.connection-test-query=SELECT 1